// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crNet.proto

/*
Package net is a generated protocol buffer package.

It is generated from these files:
	crNet.proto

It has these top-level messages:
	MsgHeader
*/
package net

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MSG int32

const (
	MSG_HEADER  MSG = 0
	MSG_HEADER1 MSG = 1
)

var MSG_name = map[int32]string{
	0: "HEADER",
	1: "HEADER1",
}
var MSG_value = map[string]int32{
	"HEADER":  0,
	"HEADER1": 1,
}

func (x MSG) String() string {
	return proto.EnumName(MSG_name, int32(x))
}
func (MSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgHeader struct {
	Cmd int32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
}

func (m *MsgHeader) Reset()                    { *m = MsgHeader{} }
func (m *MsgHeader) String() string            { return proto.CompactTextString(m) }
func (*MsgHeader) ProtoMessage()               {}
func (*MsgHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgHeader) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgHeader)(nil), "net.MsgHeader")
	proto.RegisterEnum("net.MSG", MSG_name, MSG_value)
}

func init() { proto.RegisterFile("crNet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2e, 0xf2, 0x4b,
	0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4b, 0x2d, 0x51, 0x92, 0xe5, 0xe2,
	0xf4, 0x2d, 0x4e, 0xf7, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x12, 0x12, 0xe0, 0x62, 0x4e, 0xce, 0x4d,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0xb5, 0xe4, 0xb8, 0x98, 0x7d, 0x83, 0xdd,
	0x85, 0xb8, 0xb8, 0xd8, 0x3c, 0x5c, 0x1d, 0x5d, 0x5c, 0x83, 0x04, 0x18, 0x84, 0xb8, 0xb9, 0xd8,
	0x21, 0x6c, 0x43, 0x01, 0xc6, 0x24, 0x36, 0xb0, 0x51, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x92, 0x7d, 0x78, 0xd9, 0x59, 0x00, 0x00, 0x00,
}
